## Prometheus Configuration for Kubernetes
## values.yaml

# Prometheus server settings
prometheus:
  prometheusSpec:
    # ServiceMonitor objects will be discovered in any namespace.
    serviceMonitorSelectorNilUsesHelmValues: false
    # PodMonitor objects will be discovered in any namespace.
    podMonitorSelectorNilUsesHelmValues: false
    # Enable scraping based on annotations.
    # This is an alternative to ServiceMonitors.
    scrapeConfigs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Scrape pods with the 'prometheus.io/scrape: true' annotation.
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          # Use the 'prometheus.io/path' annotation for the metrics path.
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          # Use the 'prometheus.io/port' annotation for the port.
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          # Add the pod name as a label.
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          # Add the namespace as a label.
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          # Add the pod name as a label.
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

